version: '3.9'
services:
  users_backend:
    build: .
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - users_db

  users_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root