version: '3.9'
services:
  users_backend:
    build: .
    container_name: users-ms
    volumes:
      - .:/app
    depends_on:
      - users_db
    networks:
      - users

  users_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - users

networks:
  users:
    name: users